bundle:
  groupId: "io.jenkins.tools.ci-jenkins.io.runner"
  artifactId: "jenkinsfile-runner"
  vendor: "Oleg Nenashev"
  title: "ci.jenkins.io Runner"
  description: "Emulates the ci.jenkins.io environment, as Jenkinsfile Runner"
buildSettings:
  pom: "pom.xml"
  pomSkipItself: true
  jenkinsfileRunner:
    source:
      groupId: "io.jenkins"
      artifactId: "jenkinsfile-runner"
      build:
        noCache: true
      source:
        git: https://github.com/jenkinsci/jenkinsfile-runner.git
        commit: 66626ef7c95c281d5b3ef9da9f5fdc36b4b42bf0
    docker:
      base: "jenkins/ci.jenkins.io-runner.base"
      tag: "onenashev/ci.jenkins.io-runner"
      build: true
war:
  groupId: "org.jenkins-ci.main"
  artifactId: "jenkins-war"
  source:
    version: "2.138.3"
systemProperties:
  jenkins.model.Jenkins.slaveAgentPort: "50000"
  jenkins.model.Jenkins.slaveAgentPortEnforce: "true"
  hudson.model.LoadStatistics.clock: "1000"
groovyHooks:
  - type: "init"
    id: "initScripts"
    source:
      dir: "init_scripts/src/main/groovy"
casc:
  - id: "jcasc-config"
    source:
      dir: jenkins.yaml
