bundle:
  groupId: "io.jenkins.tools.ci-jenkins.io.runner"
  artifactId: "jenkinsfile-runner"
  vendor: "Oleg Nenashev"
  title: "ci.jenkins.io Runner"
  description: "Emulates the ci.jenkins.io environment, as Jenkinsfile Runner"
buildSettings:
  pom: "pom.xml"
  pomIgnoreRoot: true
  pomIncludeWar: true
  jenkinsfileRunner:
    source:
      groupId: "io.jenkins"
      artifactId: "jenkinsfile-runner"
      build:
        noCache: true
      source:
        git: https://github.com/jenkinsci/jenkinsfile-runner.git
        branch: 1.0-beta-12
    docker:
      base: "jenkins/ci.jenkins.io-runner.base"
      tag: "jenkins4eval/ci.jenkins.io-runner:local-test"
      build: true
systemProperties:
  jenkins.model.Jenkins.slaveAgentPort: "50000"
  jenkins.model.Jenkins.slaveAgentPortEnforce: "true"
  hudson.model.LoadStatistics.clock: "1000"
groovyHooks:
  - type: "init"
    id: "initScripts"
    source:
      dir: "init_scripts/src/main/groovy"
casc:
  - id: "jcasc-config"
    source:
      dir: jenkins.yaml
