bundle:
  groupId: "io.jenkins.jenkinsfile-runner.demo"
  artifactId: "ci.jenkins.io-runner"
  vendor: "Oleg Nenashev"
  title: "ci.jenkins.io Runner"
  description: "Emulates the ci.jenkins.io environment, as Jenkinsfile Runner"
buildSettings:
  pom: "pom.xml"
  pomIgnoreRoot: true
  jenkinsfileRunner:
    source:
      groupId: "io.jenkins.jenkinsfile-runner"
      artifactId: "jenkinsfile-runner"
      source:
        version: 1.0-beta-4
    docker:
      base: "jenkins/ci.jenkins.io-runner.base"
      tag: "onenashev/ci.jenkins.io-runner"
      build: true
war:
  groupId: "org.jenkins-ci.main"
  artifactId: "jenkins-war"
  source:
    version: "2.156"
systemProperties:
  jenkins.model.Jenkins.slaveAgentPort: "50000"
  jenkins.model.Jenkins.slaveAgentPortEnforce: "true"
  hudson.model.LoadStatistics.clock: "1000"
groovyHooks:
  - type: "init"
    id: "initScripts"
    source:
      dir: "init_scripts/src/main/groovy"
casc:
  - id: "jcasc-config"
    source:
      dir: jenkins.yaml
